name: Publish Mod
on:
  workflow_dispatch:
    inputs:
      mod-version:
        description: 'Mod version:'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
    
      - name: Build
        run: ./gradlew build

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          body: |
            Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: false

      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: 9ySQVrz2
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          # curseforge-id: 394468
          # curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-tag: ${{ github.event.inputs.mod-version }}
          github-token: ${{ secrets.RELEASE_TOKEN }}
          
          files-primary: build/libs/!(*-@(unmapped|dev|sources|javadoc)).jar
          files-secondary: ''
